version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch # https://hub.docker.com/r/circleci/python/
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache: # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: deps9-{{ .Branch }}-{{ checksum "ci.txt" }}
      - run: pip install -r ci.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "ci.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run: coverage run setup.py test
      - run: codecov
